# Datei: .gitlab-ci.yml
variables:
    GIT_STRATEGY: clone
    BASE_IMAGE: webpage:base
    LINTER_IMAGE: webpage:linter
    LINKCHECKER_IMAGE: webpage:linkchecker

stages:
    - build

build_base:
    stage: build
    script:
        - docker build -t ${BASE_IMAGE} .

build_linter:
    stage: build
    script:
        - docker build -t ${LINTER_IMAGE} linter/

build_linkchecker:
    stage: build
    script:
        - docker build -t ${LINKCHECKER_IMAGE} linkchecker/
