variables:
    GIT_STRATEGY: clone
    BASE_IMAGE: webpage:base

stages:
    - build
    - test
    - cleanup
    - release

build_linter:
    stage: build
    script:
        - docker build -t ${BASE_IMAGE} .

test_mkdocs:
    stage: test
    script: docker run ${BASE_IMAGE}

test_linter:
    stage: test
    script: docker run ${BASE_IMAGE} util/lint-changes.sh

test_linkchecker:
    stage: test
    script: docker run ${BASE_IMAGE} util/check-links.sh
