variables:
    GIT_STRATEGY: clone
    DOCKER_IMAGE: webpage:all

stages:
    - build
    - test
    - release


build_linter:
    stage: build
    script: docker build -t ${DOCKER_IMAGE} .

test_mkdocs:
    stage: test
    script: docker run ${DOCKER_IMAGE}

test_linter_preview:
    stage: test
    script: docker run --rm -w /src ${DOCKER_IMAGE} doc.zih.tu-dresden.de/util/lint-changes.sh
    only: [ merge_requests ]

test_linkchecker_preview:
    stage: test
    script: docker run --rm -w /src ${DOCKER_IMAGE} doc.zih.tu-dresden.de/util/check-links.sh
    only: [ merge_requests ]

test_linter:
    stage: test
    script: docker run --rm ${DOCKER_IMAGE} markdownlint docs
    only: [ main ]

test_linkchecker:
    stage: test
    script: docker run --rm ${DOCKER_IMAGE} bash -c "find docs -type f -name '*.md' | xargs -L1 markdown-link-check --quiet"
    only: [ main ]

release:
    stage: release
    script:
        - docker run --rm -v /var/www/html/hpc-wiki:/mnt ${DOCKER_IMAGE} mkdocs build --site-dir /mnt
    only: [ main ]
