# Datei: .gitlab-ci.yml
variables:
    GIT_STRATEGY: clone
    TEST_IMAGE: webpage:${CI_COMMIT_REF_NAME}
    TEST_NETWORK: testnet

stages:
    - build

build:
    stage: build
    script:
        - pwd
        - ls -l
        - 'echo "TEST_IMAGE: ${TEST_IMAGE}"'
        - 'echo "TEST_NETWORK: ${TEST_NETWORK}"'
        - docker build -t ${TEST_IMAGE} .
